
server:
  port: 9001
spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/apnabus
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: anand123
  application:
    name: ADMIN-SERVICE

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/